version: '3.8'

services:
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 'web'
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    entrypoint: /code/entrypoint.sh