# Generated by Django 5.0 on 2023-12-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='Ожидание', max_length=64),
        ),
    ]
