# Generated by Django 4.2.6 on 2023-11-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(),
        ),
    ]
