# Generated by Django 4.2.6 on 2023-10-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('Физ. лицо', 'Natural'), ('Юр. лицо', 'Legal')], default='Юр. лицо', max_length=56),
        ),
    ]
