# Generated by Django 4.2.6 on 2023-10-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='full_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11),
        ),
    ]
