# Generated by Django 4.2.6 on 2023-10-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.IntegerField()),
                ('company', models.CharField(default='', max_length=128)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('change_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
